# Generated by Django 3.2.16 on 2022-10-18 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=130)),
                ('last_name', models.CharField(max_length=130)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Teetime',
            fields=[
                ('teetime_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teetime_date', models.DateField()),
                ('teetime_time', models.TimeField()),
                ('teetime_comments', models.TextField(blank=True, max_length=180)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('player_count', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Teetime Requested'), (1, 'Teetime Accepted')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teetime', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-teetime_date'],
            },
        ),
    ]
