# Generated by Django 3.2.16 on 2023-01-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teetime',
            name='teetime_comments',
            field=models.TextField(max_length=180, null=True),
        ),
    ]
